#!/bin/bash

PROJECT_DIR="$PWD"
DRIVER=firefox
EXPLICIT_WAIT=30
IMPLICIT_WAIT=10
TEST_ENV=QA
HEADLESS=true
SEND_MAIL=false

cd $PROJECT_DIR

echo Running Test...
echo mvn clean verify -DBROWSER=$DRIVER -DTEST_ENV=$TEST_ENV -DHEADLESS=$HEADLESS -DEXPLICIT_WAIT=$EXPLICIT_WAIT -DIMPLICIT_WAIT=$IMPLICIT_WAIT -DSEND_MAIL=$SEND_MAIL
mvn clean verify -DBROWSER=$DRIVER -DTEST_ENV=$TEST_ENV -DHEADLESS=$HEADLESS -DEXPLICIT_WAIT=$EXPLICIT_WAIT -DIMPLICIT_WAIT=$IMPLICIT_WAIT -DSEND_MAIL=$SEND_MAIL
